import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import { GetStaticProps, NextPage } from "next"
import { Header } from "@/components/layout"
import { SharedHead } from "@/components/layout/header/headUtils"
import { PagePropsProvider } from "@/lib/hooks"
import { Footer } from "@/components/layout/Footer"

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const localeProps = await serverSideTranslations(locale, ["common"])

  return {
    props: { ...localeProps },
  }
}

const DashboardPage: NextPage = ({}) => {
  return (
    <PagePropsProvider
      value={{ titleToken: "AImage", descriptionToken: "Generated by create next app" }}
    >
      <SharedHead />
      <Header className="sticky top-0" />
      <main className="w-full">
        zxcvzxcvzcx
      </main>
      <Footer />
    </PagePropsProvider>
  )
}

export default DashboardPage
