import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import Head from "next/head"
import { GetStaticProps, NextPage } from "next"
import { Header } from "@/components/layout"

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const localeProps = await serverSideTranslations(locale, ["common"])

  return {
    props: { ...localeProps },
    revalidate: 16,
  }
}

const Home: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>AImage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Header />
      <section className="px-12">landing page</section>
    </>
  )
}

export default Home
