import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import Head from "next/head"
import { GetStaticProps, NextPage } from "next"
import { Header } from "@/components/layout"
import { SharedHead } from "@/components/layout/header/headUtils"
import { PagePropsProvider } from "@/lib/hooks"

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const localeProps = await serverSideTranslations(locale, ["common"])

  return {
    props: { ...localeProps },
    revalidate: 16,
  }
}

const Home: NextPage = ({}) => {
  return (
    <PagePropsProvider
      value={{ titleToken: "AImage", descriptionToken: "Generated by create next app" }}
    >
      <SharedHead />
      <Header />
      <section className="px-12">landing page</section>
    </PagePropsProvider>
  )
}

export default Home
