import { Header } from "@/components/layout"
import { PagePropsProvider } from "@/lib/hooks"
import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import Head from "next/head"
import { useTranslation } from "next-i18next"
import { SharedHead } from "@/components/layout/header/headUtils"
import { Footer } from "@/components/layout/Footer"

export const getStaticProps = async ({ locale }) => {
  const localeProps = await serverSideTranslations(locale, ["common"])
  return {
    props: { ...localeProps },
  }
}

const PricingPage = () => {
  const { t } = useTranslation()
  return (
    <PagePropsProvider
      value={{ titleToken: "Pricing", descriptionToken: "Generated by create next app" }}
    >
      <SharedHead />
      <Header />
      <main className="px-12">{t("Pricing")}</main>
      <Footer />
    </PagePropsProvider>
  )
}

export default PricingPage
