import { Header } from "@/components/layout"
import { PagePropsProvider } from "@/lib/hooks"
import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import Head from "next/head"
import { useTranslation } from "react-i18next"

export const getStaticProps = async ({ locale }) => {
  const localeProps = await serverSideTranslations(locale, ["common"])
  return {
    props: { ...localeProps },
  }
}

const SupportPage = () => {
  const { t } = useTranslation()
  return (
    <PagePropsProvider value={{}}>
      <Head>
        <title>{t("Support")} &middot; AImage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="px-12">Support</section>
    </PagePropsProvider>
  )
}

export default SupportPage
